# Generated by Django 4.1.7 on 2023-04-03 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('whoiswho', models.CharField(default='whoiswho', max_length=1000)),
                ('to', models.CharField(default='', max_length=1000)),
                ('writer', models.CharField(blank=True, default='anonymous', max_length=1000)),
                ('mation', models.CharField(default='', max_length=10000000)),
                ('title', models.CharField(default='notitle', max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='files/')),
                ('delete', models.CharField(default='no', max_length=1000)),
                ('date', models.CharField(default='no date', max_length=1000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
