# Generated by Django 4.1.7 on 2023-04-03 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('typeof', models.CharField(default='notverified', max_length=100)),
                ('timeaactve', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('typeof', models.CharField(default='notverified', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('typeofverification', models.CharField(default='notverified', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('typeofverification', models.CharField(default='notverified', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lawyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstnamex', models.CharField(default='1', max_length=100)),
                ('Secondnamex', models.CharField(default='2', max_length=100)),
                ('company', models.CharField(default='1', max_length=100)),
                ('Sdescription', models.CharField(default='no description', max_length=100)),
                ('Ldescription', models.CharField(default='no description', max_length=10000)),
                ('quoterange', models.CharField(default='no quote', max_length=100)),
                ('licensenumber', models.CharField(default='no licence', max_length=100)),
                ('owner', models.ForeignKey(default='nocomprende', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='lawfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='category', max_length=100)),
                ('Ldescription', models.CharField(default='no description', max_length=10000)),
                ('lawyers', models.ManyToManyField(to='consultme1.lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(default='nousername', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='category', max_length=100)),
                ('Ldescription', models.CharField(default='no description', max_length=10000)),
                ('lawyers', models.ManyToManyField(to='consultme1.lawyer')),
            ],
        ),
    ]
