# Generated by Django 4.1.7 on 2023-04-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultme1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='meimagex',
            field=models.CharField(default='2', max_length=100),
        ),
    ]
